import { S } from '../utils/state.js'

export function renderAI() {
  return '<div style="max-width:700px;margin:0 auto">'
    + '<div style="background:#fff;border-radius:8px;border:1px solid #e2e8f0;padding:24px;margin-bottom:16px">'
    + '<div style="font-size:14px;font-weight:700;color:#1a1c1e;margin-bottom:8px">AI Assistant</div>'
    + '<div style="font-size:12px;color:#8a9ba8;margin-bottom:16px">Ask questions about your inventory, orders, or business data.</div>'
    + '<div id="ai-messages" style="min-height:200px;max-height:400px;overflow-y:auto;border:1px solid #e2e8f0;border-radius:6px;padding:12px;margin-bottom:12px;font-size:12px;color:#4a5568">'
    + '<div style="color:#8a9ba8;text-align:center;padding:40px 0">Ask me anything about TGK Motorsport data...</div>'
    + '</div>'
    + '<div style="display:flex;gap:8px">'
    + '<input id="ai-input" placeholder="e.g. What parts are low on stock?" '
    + ' style="flex:1;padding:10px 12px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px"'
    + ' onkeydown="if(event.key===\'Enter\')window.sendAIMessage()">'
    + '<button onclick="window.sendAIMessage()" style="padding:10px 20px;background:#2ABFAA;color:#fff;border:none;border-radius:6px;font-size:12px;font-weight:700;cursor:pointer">Send</button>'
    + '</div>'
    + '</div>'
    + '<div style="background:#fff;border-radius:8px;border:1px solid #e2e8f0;padding:16px">'
    + '<div style="font-size:11px;font-weight:700;color:#8a9ba8;text-transform:uppercase;letter-spacing:.06em;margin-bottom:10px">Quick Stats</div>'
    + '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:12px">'
    + '<div style="color:#4a5568">Parts in catalog: <strong>' + S.parts.length + '</strong></div>'
    + '<div style="color:#4a5568">Assemblies: <strong>' + S.assemblies.length + '</strong></div>'
    + '<div style="color:#4a5568">Total orders: <strong>' + S.sales.length + '</strong></div>'
    + '<div style="color:#4a5568">Open POs: <strong>' + S.purchases.filter(p=>p.status==='Ordered').length + '</strong></div>'
    + '<div style="color:#ef4444">Low stock parts: <strong>' + S.parts.filter(p=>(p.total_unpckgd||0)<(p.min_qty||0)&&(p.min_qty||0)>0).length + '</strong></div>'
    + '<div style="color:#4a5568">Active dealers: <strong>' + S.dealers.filter(d=>d.status==='Active').length + '</strong></div>'
    + '</div>'
    + '</div>'
    + '</div>'
}